# Use Node.js for frontend
FROM node:22-alpine

WORKDIR /frontend

# Copy package.json and install dependencies first (to optimize Docker caching)
COPY package.json package-lock.json ./
RUN npm install

# Copy rest of the frontend code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
